app/src/main/java/me/mudkip/moememos/ui/page/memoinput/MemoInputPage.kt
The TextField for the input of memos should behave like sentences, capitalize on each new sentences.
=> fix: auto capitalize sentences

app/src/main/AndroidManifest.xml
=> fix: numerous instances in recent menu

app/build.gradle, app/src/main/java/me/mudkip/moememos/ext/AnnotatedStringExt.kt, app/src/main/java/me/mudkip/moememos/ui/component/Markdown.kt
=> feat: markdown headings

app/src/main/java/me/mudkip/moememos/data/constant/Text.kt, app/src/main/java/me/mudkip/moememos/ui/page/memoinput/MemoInputPage.kt
=> feature: a button to add to-do item

app/src/main/java/me/mudkip/moememos/data/repository/MemoRepository.kt, app/src/main/java/me/mudkip/moememos/ui/page/memoinput/MemoInputPage.kt, app/src/main/java/me/mudkip/moememos/util/Markdown.kt
=> fix: creating new tags

app/src/main/java/me/mudkip/moememos/data/api/MemosApi.kt, app/src/main/java/me/mudkip/moememos/data/model/Memo.kt, app/src/main/java/me/mudkip/moememos/data/repository/MemoRepository.kt, app/src/main/java/me/mudkip/moememos/ui/component/ArchevedMemoCard.kt, app/src/main/java/me/mudkip/moememos/ui/component/ExploreMemoCard.kt, app/src/main/java/me/mudkip/moememos/ui/component/MemoContent.kt, app/src/main/java/me/mudkip/moememos/ui/component/MemosCard.kt, app/src/main/java/me/mudkip/moememos/ui/component/SideDrawer.kt, app/src/main/java/me/mudkip/moememos/ui/page/common/RouteName.kt, app/src/main/java/me/mudkip/moememos/ui/page/memoinput/MemoInputPage.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/ArchivedMemoList.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/ExploreList.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/ExplorePage.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/MemosNavigation.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/MemosPage.kt, app/src/main/java/me/mudkip/moememos/viewmodel/ExploreViewModel.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, build.gradle
=> feat: explore page

app/src/main/java/me/mudkip/moememos/MoeMemosFileProvider.kt
fix [68](https://github.com/mudkipme/MoeMemosAndroid/issues/68)
=> fix:can not view image

app/src/main/res/values-ru/strings.xml
As agreed in the mail, I have translated into Russian
=> add Russian translate values

app/src/main/res/values-ru/strings.xml
=> Update ru strings.xml

app/src/main/java/me/mudkip/moememos/ui/component/MemoContent.kt
=> feat: 支持图片以grid排列, 减少图片占用高度

app/build.gradle, app/src/main/java/me/mudkip/moememos/ui/component/ArchevedMemoCard.kt, app/src/main/java/me/mudkip/moememos/ui/component/ExploreMemoCard.kt, app/src/main/java/me/mudkip/moememos/ui/component/MemoContent.kt, app/src/main/java/me/mudkip/moememos/ui/component/MemosCard.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/MemosList.kt, build.gradle
=> feat: support folding and expanding posts.

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/res/xml/network_security_config.xml
=> feat: support TLS with user installed CA

.idea/kotlinc.xml, app/build.gradle, app/src/main/java/me/mudkip/moememos/data/api/MemosApi.kt, app/src/main/java/me/mudkip/moememos/data/api/MemosApiService.kt, app/src/main/java/me/mudkip/moememos/data/model/Resource.kt, app/src/main/java/me/mudkip/moememos/data/repository/MemoRepository.kt, app/src/main/java/me/mudkip/moememos/ext/DataStoreExt.kt, app/src/main/java/me/mudkip/moememos/ui/component/MemoImage.kt, app/src/main/java/me/mudkip/moememos/ui/component/SideDrawer.kt, app/src/main/java/me/mudkip/moememos/ui/component/TagDrawerItem.kt, app/src/main/java/me/mudkip/moememos/ui/page/common/Navigation.kt, app/src/main/java/me/mudkip/moememos/ui/page/login/LoginPage.kt, app/src/main/java/me/mudkip/moememos/ui/page/memoinput/MemoInputPage.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/ArchivedMemoList.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/ExploreList.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/MemosList.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/SearchPage.kt, app/src/main/java/me/mudkip/moememos/ui/page/resource/ResourceListPage.kt, app/src/main/java/me/mudkip/moememos/ui/page/settings/SettingsPage.kt, app/src/main/java/me/mudkip/moememos/viewmodel/MemosViewModel.kt, app/src/main/res/values/strings.xml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> feat: support deleting tags

app/src/main/java/me/mudkip/moememos/data/api/MemosApi.kt
=> feat: support non-root base urls

app/src/main/java/me/mudkip/moememos/data/api/MemosApiService.kt
=> fix: leak authorization to storage domain

app/src/main/java/me/mudkip/moememos/data/model/User.kt
=> fix: support for default visibility setting

app/src/main/java/me/mudkip/moememos/ui/component/SideDrawer.kt
=> fix: weekday display for heat map

app/src/main/java/me/mudkip/moememos/ui/component/MemosCard.kt, app/src/main/java/me/mudkip/moememos/viewmodel/MemosViewModel.kt
=> fix: losing visibility after toggling checkbox

app/build.gradle, app/src/main/java/me/mudkip/moememos/data/api/MemosApiService.kt, app/src/main/java/me/mudkip/moememos/data/model/Resource.kt, app/src/main/res/values-fr/strings.xml
=> fix: compatibility with Memos 0.19

app/src/main/java/me/mudkip/moememos/viewmodel/MemoInputViewModel.kt
=> feat: prevent image resizing

.idea/inspectionProfiles/Project_Default.xml, app/src/main/java/me/mudkip/moememos/data/api/MemosApiService.kt, app/src/main/java/me/mudkip/moememos/ext/DataStoreExt.kt, app/src/main/java/me/mudkip/moememos/ui/page/login/LoginPage.kt, app/src/main/java/me/mudkip/moememos/viewmodel/UserStateViewModel.kt, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
Since Login with Open ID is removed long ago in Memos and causes a few confusions, it's time to remove this feature in favor of Login with Access Token.
=> feat: remove login with open id

app/src/main/res/values-it/strings.xml, app/src/main/res/xml/locales_config.xml
Completes #155. Thanks @tombatti!
=> feat: add Italian translation by tombatti

app/src/main/java/me/mudkip/moememos/data/model/Resource.kt
=> fix: compatibility with Memos 0.21

app/build.gradle, app/src/main/java/me/mudkip/moememos/data/api/MemosV1Api.kt, app/src/main/java/me/mudkip/moememos/data/repository/MemosV1Repository.kt
We have to drop support for 0.22.0 as this is a breaking change. (0.15.0 - 0.21.0 is still supported)
=> feat: support Memos 0.22.1

app/src/main/java/me/mudkip/moememos/data/repository/MemosV1Repository.kt
=> fix: attach image to existing memo

app/src/main/java/me/mudkip/moememos/ext/AnnotatedStringExt.kt, app/src/main/java/me/mudkip/moememos/ui/component/Markdown.kt, app/src/main/java/me/mudkip/moememos/ui/component/MemosCard.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/MemosList.kt
I'm working on resolving #161 - The basic functionality is there. However, whenever I hold inside the text, onLongPress does not get triggered. Holding anywhere else inside a MemosCard works and correctly triggers the edit screen. 
Any ideas to fix this would be greatly appreciated :) I'm currently out of ideas on how to debug this.
=> initial hold to edit functionality

app/src/main/java/me/mudkip/moememos/ext/MemoExt.kt, app/src/main/java/me/mudkip/moememos/ui/component/MemosCard.kt, app/src/main/java/me/mudkip/moememos/ui/page/memos/MemosList.kt, app/src/main/java/me/mudkip/moememos/viewmodel/MemosViewModel.kt, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
Just add copy link feature
Related request #74
=> [add] Copy Note Link Feature

app/src/main/AndroidManifest.xml, app/src/main/java/me/mudkip/moememos/ui/page/common/Navigation.kt, app/src/main/res/drawable/ic_shortcut_add.xml, app/src/main/res/drawable/ic_shortcut_search.xml, app/src/main/res/xml/shortcuts.xml
Add app shortcuts for composing and searching memos
=> feat: Add app shortcuts for composing and searching memos
